import { lazy } from "react";

export const Articles = lazy(() => import('./Articles'))
export const Article = lazy(() => import('./Article'))
export const CreateArticle = lazy(() => import('./CreateArticle'))
export const CreateImage = lazy(() => import('./CreateImage'))
export const CreateQuestion = lazy(() => import('./CreateQuestion') )
export const Cart = lazy(() => import('./Cart'))
export const Forum = lazy(() => import('./Forum'))
export const Gallery = lazy(() => import('./Gallery'))
export const Home = lazy(() => import('./Home'))
export const Profile = lazy(() => import('./Profile/Profile'))
export const Product = lazy(() => import('./Product'))
export const Question = lazy(() => import('./Question'))
export const Signin = lazy(() => import('./Signin'))
export const Shop = lazy(() => import('./Shop'))
export const UserProfile = lazy(() => import('./Profile/UserProfile'))
